name: noteyou
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.7 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

  # State Management
  flutter_riverpod: ^2.6.1

  # Fonts & Styling
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3

  # Core Functionality
  record: ^6.2.0
  audioplayers: ^6.5.1
  shared_preferences: ^2.5.4
  google_generative_ai: ^0.4.7
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  flutter_local_notifications: ^17.2.1+2
  flutter_timezone: ^3.0.1
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
